(define (domain WAREHOUSE)
  (:requirements :strips :typing :durative-actions :numeric-fluents)
  (:types crate crate_group loader mover)
  (:predicates (EMPTY_L ?l - loader)
                (loading ?l - loader ?c - crate)
                (EMPTY_M ?m - mover)
                (moving ?m - mover ?c - crate)
                (on_shelf ?c - crate)
                (on_mover ?c - crate ?m - mover)
                (on_loading_bay ?c - crate)
                (on_loader ?c - crate ?l - loader)
                (on_conveyor_belt ?c - crate)
                (of_group ?c - crate ?g crate_group)
	       )
  (:functions (at_distance ?c - crate)
                (weights ?c - crate)
            )

; (:action pick
; 	     :parameters (?l - loader ?l - crate)
; 	     :precondition ()
; 	     :effect ()
; 	     )

; (:durative-actions light_move
;       :parameters  (?l - mover ?c - crate)
;       :duration (= ?duration (/ (* (at_distance ?c) (weights ?c)) 100))
;       :condition (and ((> (weights ?c) 50.0)
;                         (on_mover ?c ?l))
;       )
;       :effect ((=(at_distance ?c) 0)
;       )
; )

)
