(define (problem warehouse-2-ext4213)
  (:domain warehouse-crates-4213)
  (:objects 
    m1 m2 - mover
    c1 c3 c4 - normal_crate
    c2 - fragile_crate  
    fl - full_loader
    sl - side_loader
    A B - group
    st1 st2 - charging_station
  )
  (:init
    (independent m1 m2)
    (independent m2 m1)
    (empty m1)
    (empty m2)
    (at_pause m1)
    (at_pause m2)
    (at_loading_bay m1)
    (at_loading_bay m2)
    (= (battery-capacity m1) 20)
    (= (battery-capacity m2) 20)
    (empty fl)
    (idle fl)
    (empty sl)
    (idle sl)
    (on_shelf c1)
    (on_shelf c2)
    (on_shelf c3)
    (on_shelf c4)
    (pickable c1)
    (pickable c2)
    (pickable c3)
    (pickable c4)
    (= (weight c1) 70)
    (= (weight c2) 80)
    (= (weight c3) 20)
    (= (weight c4) 30)
    (= (distance c1) 10)
    (= (distance c2) 20)
    (= (distance c3) 20)
    (= (distance c4) 10)
    (no_active_group)
    (is_of_group A c1)
    (is_of_group A c2)
    (is_of_group B c3)
    (is_of_group B c4)
    (= (group-cost) 0)
    (free st1)
    (free st2)
    (= (charging_vel st1) 2) ;charging 2 units of battery by unit of time
    (= (charging_vel st2) 2)
    (= (battery m1) 20)
    (= (battery m2) 20)
    )
  (:goal
    (and (loaded c1)
        (loaded c2)
        (loaded c3)
        (loaded c4)
    ))
  (:metric minimize (+ (total-time) (group-cost)))
  )
